// Copyright (C) RedCraft86. Licensed under LGPL-3.0, see LICENSE file for details.

#pragma once

#include "Engine/LatentActionManager.h"

/**
 * Constructs latent action metadata using a shared sequence of positive int32 IDs.
 * Latent actions are identified by callback target and UUID. IDs eventually repeat
 * and are not reserved against active actions or IDs generated by other producers.
 * Calls require the game thread, including builds where assertions are disabled.
 */
class TOROCORE_API FLatentInfo final
{
	/** Next ID in the shared sequence, starting at 1000 and wrapping after INT32_MAX. */
	static inline int32 LatentId = 1000;

public:

	/**
	 * Constructs metadata with a fresh sequence ID and linkage zero; does not register an action.
	 * Call only from the game thread. A working callback requires a valid target and a
	 * compatible reflected function that accepts the latent continuation linkage.
	 * @param Target Callback target; may be left null for the caller to fill afterward.
	 * @param FuncName Reflected callback function name; may be filled afterward when empty.
	 * @return Metadata containing the supplied callback fields, linkage zero, and the next ID.
	 */
	[[nodiscard]] static FLatentActionInfo Make(UObject* Target = nullptr, const FString& FuncName = FString())
	{
		checkf(IsInGameThread(), TEXT("FLatentInfo::Make(...) should only be called from the GameThread."));
		return FLatentActionInfo(0, NextId(), *FuncName, Target);
	}

	/**
	 * Returns the next ID from 1000 through INT32_MAX - 1, then repeats from 1000.
	 * Call only from the game thread. Does not check for existing actions or reserve the ID;
	 * callers must avoid collisions with active actions on the same callback target.
	 */
	[[nodiscard]] static int32 NextId()
	{
		checkf(IsInGameThread(), TEXT("FLatentInfo::NextId(...) should only be called from the GameThread."));
		if (LatentId == TNumericLimits<int32>::Max())
		{
			LatentId = 1000;
		}

		return LatentId++;
	}
};
